# cutom tokanizer exception word list to leave out the topics in the result summary

ai_topics = [
    "AI",
    "deep learning",
    "reinforcement learning",
    "machine learning",
    "supervised learning",
    "unsupervised learning",
    "semi-supervised learning",
    "self-supervised learning",
    "neural networks",
    "convolutional neural networks",
    "recurrent neural networks",
    "long short-term memory",
    "LSTM",
    "gated recurrent unit",
    "GRU",
    "transformers",
    "BERT",
    "GPT",
    "XLNet",
    "Roberta",
    "language model",
    "large language model",
    "LLM",
    "multi-layer perceptron",
    "MLP",
    "autoencoder",
    "variational autoencoder",
    "VAE",
    "generative adversarial networks",
    "GAN",
    "cycle GAN",
    "predictive modeling",
    "regression",
    "linear regression",
    "logistic regression",
    "classification",
    "clustering",
    "k-means clustering",
    "hierarchical clustering",
    "density-based spatial clustering",
    "DBSCAN",
    "support vector machines",
    "SVM",
    "decision trees",
    "random forest",
    "gradient boosting",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "ensemble methods",
    "bagging",
    "boosting",
    "stacking",
    "restacking",
    "AdaBoost",
    "multi-layer modeling",
    "dropout",
    "batch normalization",
    "layer normalization",
    "training",
    "model training",
    "validation",
    "cross-validation",
    "hyperparameter tuning",
    "grid search",
    "random search",
    "Bayesian optimization",
    "early stopping",
    "learning rate",
    "optimizer",
    "SGD",
    "Adam",
    "RMSprop",
    "momentum",
    "loss function",
    "cross-entropy loss",
    "mean squared error",
    "MSE",
    "activation function",
    "ReLU",
    "sigmoid",
    "tanh",
    "softmax",
    "Hopfield network",
    "Markov decision process",
    "MDP",
    "Q-Learning algorithm",
    "Frozen Lake",
    "policy gradient",
    "deep Q-network",
    "DQN",
    "actor-critic",
    "A3C",
    "PPO",
    "TRPO",
    "embedding",
    "word embedding",
    "word2vec",
    "GloVe",
    "fastText",
    "clustering",
    "dimensionality reduction",
    "PCA",
    "t-SNE",
    "UMAP",
    "anomaly detection",
    "outlier detection",
    "time series analysis",
    "sequence modeling",
    "HMM",
    "Hidden Markov Model",
    "Retrieval Augmented Generation",
    "MLM",
    "Masked Language Model",
    "Approximate Nearest Neighbour",
    "product quantization",
    "Hierarchical Navigable Small World",
    "HNSW",
    "VQA",
    "Visual Question Answering",
    "object detection",
    "image segmentation",
    "semantic segmentation",
    "instance segmentation",
    "YOLO",
    "SSD",
    "Faster R-CNN",
    "U-Net",
    "GANs",
    "CycleGAN",
    "Pix2Pix",
    "StyleGAN",
    "latent space",
    "latent variable",
    "reinforcement learning",
    "policy learning",
    "reward function",
    "state space",
    "action space",
    "exploration vs exploitation",
    "Temporal Difference Learning",
    "TD Learning",
    "SARSA",
    "multi-armed bandit",
    "contextual bandit",
    "deep reinforcement learning",
    "off-policy learning",
    "on-policy learning",
    "policy iteration",
    "value iteration",
    "fuzzy logic",
    "genetic algorithms",
    "evolutionary algorithms",
    "swarm intelligence",
    "particle swarm optimization",
    "ant colony optimization",
    "neuroevolution",
    "meta-learning",
    "few-shot learning",
    "zero-shot learning",
    "one-shot learning",
    "transfer learning",
    "domain adaptation",
    "multi-task learning",
    "self-attention",
    "attention mechanism",
    "scaled dot-product attention",
    "multi-head attention",
    "positional encoding",
    "encoder-decoder architecture",
    "seq2seq",
    "text generation",
    "text classification",
    "sentiment analysis",
    "named entity recognition",
    "NER",
    "part-of-speech tagging",
    "POS tagging",
    "parsing",
    "dependency parsing",
    "constituency parsing",
    "language modeling",
    "tokenization",
    "subword tokenization",
    "byte pair encoding",
    "BPE",
    "sentencepiece",
    "attention is all you need",
    "transformer models",
    "self-supervised learning",
    "contrastive learning",
    "simCLR",
    "MoCo",
    "BYOL",
    "Siamese networks",
    "triplet loss",
    "contrastive loss",
    "pairwise learning",
    "metric learning",
    "distance metric",
    "cosine similarity",
    "euclidean distance",
    "manhattan distance",
    "mahalanobis distance",
    "Hamming distance",
    "Jaccard index",
    "Silhouette score",
    "Davies-Bouldin index",
    "Calinski-Harabasz index",
    "precision",
    "recall",
    "F1 score",
    "confusion matrix",
    "ROC curve",
    "AUC-ROC",
    "precision-recall curve",
    "average precision",
    "accuracy",
    "bias-variance tradeoff",
    "overfitting",
    "underfitting",
    "regularization",
    "L1 regularization",
    "L2 regularization",
    "dropout regularization",
    "weight decay",
    "early stopping",
    "batch size",
    "epochs",
    "learning rate schedule",
    "cyclical learning rate",
    "learning rate annealing",
    "data augmentation",
    "dropout",
    "batch normalization",
    "layer normalization",
    "instance normalization",
    "group normalization",
    "adversarial examples",
    "adversarial attacks",
    "gradient descent",
    "stochastic gradient descent",
    "mini-batch gradient descent",
    "momentum",
    "Nesterov momentum",
    "RMSprop",
    "Adam",
    "AdaGrad",
    "AdaDelta",
    "Nadam",
    "hyperparameters",
    "activation function",
    "softmax",
    "ReLU",
    "sigmoid",
    "tanh",
    "leaky ReLU",
    "ELU",
    "SELU",
    "maxout",
    "Swish",
    "GELU",
    "PReLU",
    "activation function",
    "gradient descent",
    "optimization algorithms",
    "neural network architectures",
    "regularization techniques",
    "loss functions",
    "evaluation metrics",
    "model interpretation",
    "explainable AI",
    "interpretability",
    "deep feature visualization",
    "attribution methods",
    "integrated gradients",
    "LIME",
    "SHAP",
    "grad-CAM",
    "saliency maps",
    "CAM",
    "visual explanations",
    "adversarial attacks",
    "model fairness",
    "bias in AI",
    "fairness metrics",
    "algorithmic bias",
    "privacy-preserving AI",
    "differential privacy",
    "homomorphic encryption",
    "secure multi-party computation",
    "federated learning",
    "alignment problem",
    "value alignment",
    "reward hacking",
    "corrigibility",
    "scalable oversight",
    "interpretability",
    "robustness",
    "alignment",
    "integrity",
    "security",
    "privacy",
    "accountability",
    "transparency",
    "multi-agent systems",
    "game theory",
    "cooperative game theory",
    "non-cooperative game theory",
    "Nash equilibrium",
    "zero-sum games",
    "non-zero-sum games",
    "Bayesian games",
    "Markov games",
    "evolutionary game theory",
    "multi-agent reinforcement learning",
    "social dilemmas",
    "tragedy of the commons",
    "public goods game",
    "prisoner's dilemma",
    "stag hunt",
    "battle of the sexes",
    "matching pennies",
    "coordination game",
    "repeated games",
    "iterated prisoner's dilemma",
    "communication in multi-agent systems",
    "emergent communication",
    "grounded language learning",
    "multi-agent communication",
    "linguistic coordination",
    "referential games",
    "multi-agent learning",
    "centralized training with decentralized execution",
    "decentralized training with centralized execution",
    "fully decentralized learning",
    "cooperative learning",
    "competitive learning",
    "collaborative filtering",
    "content-based filtering",
    "hybrid recommendation systems",
    "user-item collaborative filtering",
    "item-item collaborative filtering",
    "latent factor models",
    "matrix factorization",
    "alternating least squares",
    "deep learning for recommendation",
    "neural collaborative filtering",
    "session-based recommendation",
    "sequence-aware recommendation",
    "time-aware recommendation",
    "context-aware recommendation",
    "multi-criteria recommendation",
    "explainable recommendation",
    "fair recommendation",
    "privacy-preserving recommendation",
    "adversarial recommendation",
    "conversational recommendation",
    "reinforcement learning for recommendation",
    "multi-stakeholder recommendation",
    "reinforcement learning for dialogue systems",
    "end-to-end dialogue systems",
    "task-oriented dialogue systems",
    "open-domain dialogue systems",
    "generation-based dialogue systems",
    "retrieval-based dialogue systems",
    "sequence-to-sequence models for dialogue",
    "transformer models for dialogue",
    "BERT for dialogue",
    "GPT for dialogue",
    "policy gradient methods for dialogue",
    "actor-critic methods for dialogue",
    "hierarchical reinforcement learning for dialogue",
    "multi-agent dialogue systems",
    "adversarial training for dialogue systems",
    "meta-learning for dialogue systems",
    "natural language understanding",
    "intent detection",
    "slot filling",
    "named entity recognition",
    "NLU",
    "natural language generation",
    "text-to-text generation",
    "text-to-speech synthesis",
    "NLG",
]
